kind: Deployment
apiVersion: cci/v2
metadata:
  name: cae-frontend
  namespace: sercan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cae-frontend
  template:
    metadata:
      labels:
        app: cae-frontend
    spec:
      containers:
        - name: cae-frontend
          image: swr.tr-west-1.myhuaweicloud.com/devrim/IMAGE_PLACEHOLDER
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
      dnsPolicy: Default
      imagePullSecrets:
        - name: imagepull-secret
