apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-nodejs
  template:
    metadata:
      labels:
        app: sample-app-nodejs
      annotations:
        backup.velero.io/backup-volumes: data
    spec:
      containers:
        - name: sample-app-nodejs
          image: docker-server/docker-org/sample-app-nodejs:image-version
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sample-app-nodejs-pvc
      dnsPolicy: Default
      imagePullSecrets:
        - name: default-secret
