kind: Deployment
apiVersion: cci/v2
metadata:
  name: sample-app-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-nodejs
  template:
    metadata:
      labels:
        app: sample-app-nodejs
    spec:
      containers:
        - name: sample-app-nodejs
          image: docker-server/docker-org/sample-app-nodejs:image-version
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      dnsPolicy: Default
      imagePullSecrets:
        - name: imagepull-secret
