name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: Huawei 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      #- name: Build project
      #  run: npm run build

      - name: build images
        run: docker build -t cae-frontend:1.0.0 .
 
      - name: Login to SWR
        run: docker login -u tr-west-1@${{ secrets.HUAWEI_SECRET_ACCESS_KEY}} -p ${{ secrets.HUAWEI_DOCKER_SECRET }} swr.tr-west-1.myhuaweicloud.com
 
      - name: Push to SWR
        run: |
          docker tag cae-frontend:1.0.0 swr.tr-west-1.myhuaweicloud.com/devrim/cae-frontend:1.0.0
          docker push swr.tr-west-1.myhuaweicloud.com/devrim/cae-frontend:1.0.0

      # Download and install Huawei Cloud CLI.
      - name: Install HuaweiCloud CLI
        run: |
          curl -sSL https://cn-north-4-hdn-koocli.obs.cn-north-4.myhuaweicloud.com/cli/latest/hcloud_install.sh -o ./hcloud_install.sh && sudo bash ./hcloud_install.sh -y

      # Configure Huawei Cloud CLI.
      - name: Configure HuaweiCloud CLI
        run: |
          sudo hcloud configure set \
            --cli-profile=testAKSK \
            --cli-mode=AKSK \
            --cli-region=tr-west-1 \
            --cli-access-key="${{ secrets.HUAWEI_SECRET_ACCESS_KEY }}" \
            --cli-secret-key="${{ secrets.HUAWEI_SECRET_SECRET_KEY }}" \
            --cli-project-id=afda03ce061d48409cc9ec203be48407 \
            --cli-domain-id=5c438484e64d46caa7bca8e7d583de90 \
            --cli-read-timeout=20 \
            --cli-connect-timeout=10


      # Deploy Huawei Cloud CLI to CAE.
      - name: Deploy to CAE
        id: cli-command
        run: |
          echo y | sudo hcloud CAE ExecuteAction --cli-region="tr-west-1" --project_id="afda03ce061d48409cc9ec203be48407" --X-Enterprise-Project-ID="39555f42-30b1-4053-ba63-15ebf605b871" --X-Environment-ID="5263fbd9-d728-4e8a-8407-d6d180d13081" --application_id="05a04718-fb36-46de-9cbb-128413557fca" --component_id="444bb8de-a365-401b-9141-f005ba45b0fb" --api_version="v1" --kind="Action" --metadata.name="upgrade" --metadata.annotations.version="1.0.0" --spec.source.type="image" --spec.source.url="swr.tr-west-1.myhuaweicloud.com/devrim/cae-frontend:1.0.0"

      - name: Print CLI command result
        run: |
          echo "Huawei Cloud CLI command output: ${{ steps.cli-command.outputs.result }}"
